services:
  api-gateway:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    env_file:
      - apps/api-gateway/.env
    ports:
      - '3001:3001'
    volumes:
      - ./apps/api-gateway:/usr/src/app/apps/api-gateway
      - ./libs:/usr/src/app/libs
      - ./prisma:/usr/src/app/prisma
    depends_on:
      postgres:
        condition: service_healthy
  auth:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - apps/auth/.env
    volumes:
      - ./apps/auth:/usr/src/app/apps/auth
      - ./libs:/usr/src/app/libs
      - ./prisma:/usr/src/app/prisma
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
  files:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/files/Dockerfile
    env_file:
      - apps/files/.env
    volumes:
      - ./apps/files:/usr/src/app/apps/files
      - ./libs:/usr/src/app/libs
      - ./prisma:/usr/src/app/prisma
    ports:
      - '3003:3003'
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
  rabbitmq:
    image: rabbitmq:4.1.0-management
    hostname: rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  pgdata:
    driver: local
  rabbitmq:
    driver: local