services:
  api-gateway:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    env_file:
      - apps/api-gateway/.env.test
    ports:
      - '3002:3001'
    volumes:
      - ./apps/api-gateway:/usr/src/app/apps/api-gateway
      - ./libs:/usr/src/app/libs
      - ./prisma:/usr/src/app/prisma
      - ./e2e:/usr/src/app/e2e
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      clamav:
        condition: service_healthy
  auth:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - apps/auth/.env.test
    volumes:
      - ./apps/auth:/usr/src/app/apps/auth
      - ./libs:/usr/src/app/libs
      - ./prisma:/usr/src/app/prisma
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      clamav:
        condition: service_healthy
  files:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/files/Dockerfile
    env_file:
      - apps/files/.env.test
    volumes:
      - ./apps/files:/usr/src/app/files/auth
      - ./libs:/usr/src/app/libs
      - ./prisma:/usr/src/app/prisma
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      clamav:
        condition: service_healthy
  antivirus:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/antivirus/Dockerfile
    env_file:
      - apps/antivirus/.env
    volumes:
      - ./apps/antivirus:/usr/src/app/apps/antivirus
      - ./libs:/usr/src/app/libs
      - ./prisma:/usr/src/app/prisma
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      clamav:
        condition: service_healthy
  postgres:
    image: postgres:latest
    env_file:
      - .env.test
    ports:
      - '5433:5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata-test:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
  rabbitmq:
    image: rabbitmq:4.1.0-management
    hostname: rabbitmq
    restart: always
    env_file:
      - .env.test
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    ports:
      - "3310:3310"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "clamdscan", "--version" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata-test:
    driver: local
  rabbitmq:
    driver: local