-- CreateEnum
CREATE TYPE "FileStatus" AS ENUM ('PENDING', 'SCANNING', 'CLEAN', 'INFECTED', 'FAILED');

-- AlterTable
ALTER TABLE "File" ADD COLUMN     "status" "FileStatus" NOT NULL DEFAULT 'PENDING',
ALTER COLUMN "size" DROP NOT NULL;
